### ISSUE TITLE
Deploy to Github Pages: All jobs have failed

### ISSUE THREAD

**Issue by IhnwhiHeo** [hugo-toha/toha#1049]
Hi folks,

My website was working fine until last week. However, I encountered an error during deployment today. You can find the details [here](https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/14416216659).

Does anyone know how to fix this issue? Thank you.

**Comment by hossainemruz** [comment]
I can confirm the issue. I will look into it.

**Comment by IhnwhiHeo** [comment]
Thank you @hossainemruz. Please let me know if this issue is figured out.

**Comment by hossainemruz** [comment]
Should be fixed by https://github.com/hugo-toha/toha/pull/1050

**Comment by IhnwhiHeo** [comment]
Hello @hossainemruz,
I tried updating the website, but again, the same error message was found: https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/14451265677. Could you check this again?

**Comment by TUp1** [comment]
Works now ... thank you!

**Comment by hossainemruz** [comment]
> Hello [@hossainemruz](https://github.com/hossainemruz), I tried updating the website, but again, the same error message was found: [IhnwhiHeo/ihnwhiheo.github.io/actions/runs/14451265677](https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/14451265677). Could you check this again?

You have to use pull the main branch. Currently, you are using `v4.7.0`

**Comment by IhnwhiHeo** [comment]
@hossainemruz  It still does not work. I downloaded the main source zip folder and overwrote it on the local files in my machine. It shows the following error messages: https://github.com/IhnwhiHeo/ihnwhiheo.github.io/actions/runs/14453034659/job/40529947542

**Comment by hossainemruz** [comment]
Run this command to get changes from `main` branch.
```bash
hugo mod get github.com/hugo-toha/toha/v4@main
```

**Comment by IhnwhiHeo** [comment]
Thank you. But I got the following error messages:

```
(base) ➜  ~ git:(main) ✗ hugo mod get github.com/hugo-toha/toha/v4@main
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
Error: failed to get ["github.com/hugo-toha/toha/v4@main"]: failed to execute 'go [get github.com/hugo-toha/toha/v4@main]': failed to execute binary "go" with args [get github.com/hugo-toha/toha/v4@main]: go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
 *errors.errorString
```

**Comment by hossainemruz** [comment]
I believe your default branch is **source** not **main**.

**Comment by IhnwhiHeo** [comment]
When I looked at my repository, there was no main branch.
![Image](https://github.com/user-attachments/assets/f88b187e-3f94-4572-997f-757853de4f0c)

**Comment by IhnwhiHeo** [comment]
Wait.. that makes sense. I have just rerun that command again in my website repo.. I will update you soon..

**Comment by IhnwhiHeo** [comment]
Well, that worked itself, but now I lost my website like this.. could you look into this please? @hossainemruz 

![Image](https://github.com/user-attachments/assets/1a824d72-9525-4bf5-b038-9a0e36e3db77)

**Comment by hossainemruz** [comment]
Does not look like anything related to my changes. Make sure your github page settings are pointing to right branch.
